name: Awesome Action

on: ['push']

jobs:
  awesome:
    name: Awesome Action
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: PhilippeRacicot/githubactiontest
          token: ${{ secrets.GIT_HUB_TOKEN }}   # stored in GitHub secrets
          path: actions
      - name: check dir
        run: ls
      - name: ret
        run: cd ..
      - name: check dir2
        run: ls
      - name: Hello world action step
        id: hello
        uses: ./actions/main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: test
          uses: ./actions/test