name: Awesome Action

on: ['push']

jobs:
  my_first_job:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Hello world action step
       id: hello
       uses: ./githubactiontest/main
       with:
         who-to-greet: 'Mona the Octocat'
     - name: Get the output time
       run: echo "The time was ${{ steps.hello.outputs.time }}"
     - name: test
         id: hello
         uses: ./githubactiontest/test

