name: Awesome Action

on: ['push']

jobs:
  awesome:
    name: Awesome Action
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: PhilippeRacicot/githubactiontest
          ref: v1
          token: ${{ secrets.GIT_HUB_TOKEN }}   # stored in GitHub secrets
          path: .github/workflows/greetings
      - name: Run My Action
        uses: ./..github/workflows/greetings
