name: Awesome Action

on: ['push']

jobs:
  my_first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Copy submodules
       shell: bash
       run: |
          git submodule init
          git submodule update
     - name: Hello world action step
       id: hello
       uses: ./githubactiontest/workflows/main
       with:
         who-to-greet: 'Mona the Octocat'
     - name: Get the output time
       run: echo "The time was ${{ steps.hello.outputs.time }}"
